name: Test on PR
on:
  pull_request:
    branches: [main]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BUTTONSWAP_CORE_CI_TOKEN }}
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Production contracts are within size limits
        run: |
          forge --version
          forge build --sizes --skip */test/** --skip */script/**
        id: build-sizes

      - name: All contracts build successfully
        run: |
          forge --version
          forge build
        id: build

      - name: Run Forge tests (excluding known issues)
        run: |
          forge test -vvv --no-match-path 'test/known-issues/**'
        id: test

      - name: Run Forge Coverage
        run: |
          forge coverage > ./coverage-report.md
        id: coverage

      - name: Report Coverage in PR
        uses: thollander/actions-comment-pull-request@v2.3.1
        with:
          filePath: ./coverage-report.md
          comment_tag: coverage-report
